### PR TITLE
Command line options to preheat and home

### PR DESCRIPTION
**Pull request by sillyfrog**
This PR provides new command line options to pre-heat the tools (both extruder 1 & 2), the bed, and home everything.

It's very much targeted for 3D printing where preheating is relevant.

**IMPORTANT - this only implements the SACP protocol** - I have an Artisan, and that's all I can test against, but I think it'll work against other printers that use the SACP protocol.

PS: This is my first `go` project, so hopefully the code is not too nasty.

Thanks!

### CODE REVIEW

**Comment by macdylan** [comment]
Thanks, the code is great, but I'm sorry I didn't understand why we need to execute the preheat in the command line.
Can you describe use cases?

And to me, it is very dangerous for the machine to exec HOME out of sight, such as knocking over the filament in front of the bed.

**Comment by sillyfrog** [comment]
Thanks! For me I have my printer downstairs, and my computer is upstairs. So when I'm nearly finished designing something I turn on the printer (it is plugged into a WiFi smart switch), and start everything preheating. That way when I get downstairs it's ready for me to load the filament and start printing right away. I also find preheating the entire enclosure helps with bed adhesion, so can take 10-15 minutes, and having this means I don't need to go up and down (or what I was doing is opening Luban, which homes, and then getting it to start preheating by setting the tool and bed temperature).

I always leave my printer in a known state (ie: filament unloaded, and enclosure closed), but I totally understand if you feel it's too risky for others, I can keep this in my fork and we can close this PR.

Cheers.

**Comment by macdylan** [comment]
You have good habits👍, but I have some bad memories (breaking my printer :(

**Comment by macdylan** [comment]
I think i can accept this PR and leave the choice to users.

**Comment by sillyfrog** [comment]
Thanks! :)

**Pull request merged**
